// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR94wCX_IsLj1dcItjp0JtcrU6iS9QIyU',
    appId: '1:43538759775:web:3645c9f30e413e3f4d9bea',
    messagingSenderId: '43538759775',
    projectId: 'coffee-client-304f5',
    authDomain: 'coffee-client-304f5.firebaseapp.com',
    storageBucket: 'coffee-client-304f5.appspot.com',
    measurementId: 'G-ZHZKRCCREK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjgi6LHIvslQLMHRWFyL7xF9G-L70CIuU',
    appId: '1:43538759775:android:5cb27e3d0049c5494d9bea',
    messagingSenderId: '43538759775',
    projectId: 'coffee-client-304f5',
    storageBucket: 'coffee-client-304f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7sPJ3sLa7RQfo_3MH8gDnoIbxSxaihIM',
    appId: '1:43538759775:ios:e0c662066b19b2cb4d9bea',
    messagingSenderId: '43538759775',
    projectId: 'coffee-client-304f5',
    storageBucket: 'coffee-client-304f5.appspot.com',
    iosClientId: '43538759775-ab0gd3nhl613dc1lvfsjjqbaldd12j5l.apps.googleusercontent.com',
    iosBundleId: 'com.uit.coffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7sPJ3sLa7RQfo_3MH8gDnoIbxSxaihIM',
    appId: '1:43538759775:ios:e0c662066b19b2cb4d9bea',
    messagingSenderId: '43538759775',
    projectId: 'coffee-client-304f5',
    storageBucket: 'coffee-client-304f5.appspot.com',
    iosClientId: '43538759775-ab0gd3nhl613dc1lvfsjjqbaldd12j5l.apps.googleusercontent.com',
    iosBundleId: 'com.uit.coffee',
  );
}
