generate__launcher_icons:
	flutter pub run flutter_launcher_icons

generate_language_l10n:
	flutter gen-l10n

generate_project:
	dart run build_runner build

generate_project_delete_conflict:
	dart run build_runner build --delete-conflicting-outputs

generate_project (Deprecated):
	flutter pub run build_runner build

generate_project_delete_conflict (Deprecated):
	flutter pub run build_runner build --delete-conflicting-outputs
