// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3xRDHAy6mYwtyPHcEXCafHtuPKwPPqCc',
    appId: '1:140370042684:web:427f8f2e3d1c359c670839',
    messagingSenderId: '140370042684',
    projectId: 'coffee-23d02',
    authDomain: 'coffee-23d02.firebaseapp.com',
    storageBucket: 'coffee-23d02.appspot.com',
    measurementId: 'G-5T7YTBR0N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhURWj6wXyxd4gzADpJsPw8BN4xZwyd_w',
    appId: '1:140370042684:android:6431140bd75ec21f670839',
    messagingSenderId: '140370042684',
    projectId: 'coffee-23d02',
    storageBucket: 'coffee-23d02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUzVjOo1872CDmPRd9DWWaNudr6xzQQ5Q',
    appId: '1:140370042684:ios:a7ddce9c54f0a383670839',
    messagingSenderId: '140370042684',
    projectId: 'coffee-23d02',
    storageBucket: 'coffee-23d02.appspot.com',
    androidClientId: '140370042684-ivaash0i0n1iiq6mlebq8fura9t17vpq.apps.googleusercontent.com',
    iosClientId: '140370042684-4qvvvqtbnoao01dtn5h49h9f98d0se0b.apps.googleusercontent.com',
    iosBundleId: 'com.uit.coffeeAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUzVjOo1872CDmPRd9DWWaNudr6xzQQ5Q',
    appId: '1:140370042684:ios:a7ddce9c54f0a383670839',
    messagingSenderId: '140370042684',
    projectId: 'coffee-23d02',
    storageBucket: 'coffee-23d02.appspot.com',
    androidClientId: '140370042684-ivaash0i0n1iiq6mlebq8fura9t17vpq.apps.googleusercontent.com',
    iosClientId: '140370042684-4qvvvqtbnoao01dtn5h49h9f98d0se0b.apps.googleusercontent.com',
    iosBundleId: 'com.uit.coffeeAdmin',
  );
}
